### ISSUE TITLE
Does not work with Safari

### ISSUE THREAD

**Issue by shtukas** [VictorBjelkholm/ipfsbin#19]
Console says: 
ReferenceError: Can't find variable: fetch

![screen shot 2015-10-23 at 12 21 03](https://cloud.githubusercontent.com/assets/6035518/10691385/914e7ce0-7980-11e5-934b-a0960a62f917.png)

**Comment by victorb** [comment]
Hah, Safari is always behind... But yeah, simple fix for this, will deploy tomorrow.

Thanks a lot for the report!

**Comment by victorb** [comment]
Should work now! Please try out the new version and let me know if it doesn't/does work

**Comment by shtukas** [comment]
I confirm. Awesome. You're star!

**Comment by daffodilsoftwares** [comment]
@VictorBjelkholm How did you solve this error "Console says: 
ReferenceError: Can't find variable: fetch"
I am facing the same issues on Mac safari

**Comment by victorb** [comment]
Hm, should be fixed already. Try clearing your cache in the browser, you might be using an old version.

**Comment by shtukas** [comment]
Oh, thanks for coming back to me. I have just tried to access http://ipfsbin.xyz , with the latest (?) Safari (version 9.1.1). The process is stuck at the "Loading" step, and the console shows 

"SyntaxError: Cannot declare a parameter named 'mask' as it shadows the name of a strict mode function."

Cheers, 

ps: Works fine in Chrome, Firefox and Opera.
