### ISSUE TITLE
url copied to clipboard when saving

### ISSUE THREAD

**Issue by murum** [VictorBjelkholm/ipfsbin#34]
When a user saves the code it would be nice to have the address copied to clipboard

**Comment by victorb** [comment]
Good idea! Would be nice! I'm thinking though, that it might not be what the user expects... Would appreciate more feedback about this.

**Comment by sknebel** [comment]
Never mess with users' clipboards automatically, but maybe highlight a button to do so/offer a shortcut?

**Comment by murum** [comment]
I think sknebel has a good point, maybe have another button "save + copy url".

**Comment by victorb** [comment]
Yeah, probably go with something like "Copy URL to clipboard" button next to the "Save" button

**Comment by victorb** [comment]
Hm, I've decided against this. It's not very hard to copy the URL once after you saved it.
