### ISSUE TITLE
Raw mode to store the past as text without json

### ISSUE THREAD

**Issue by Faleidel** [VictorBjelkholm/ipfsbin#70]
In some cases you want the past to be compatible with other things. Right now accessing a past on ipfs.io/ipfs give you something like this `{"text":"Hello test","mode":"JavaScript"}`. It would be nice to have a mode where it simply store `Hello test`.

**Comment by fbaiodias** [comment]
:+1:

**Idea:** instead of storing the `text` directly inside the `json` file, add it to IPFS first and store the `hash` on the `json` file instead :)

**Comment by victorb** [comment]
I'm happy to say this have been implemented now! If you save a paste as "Plain Text", it'll just save the text as text in IPFS, without wrapping it in a JSON object. And if you load something in IPFSBin that is not JSON parsable, it'll show as plain text.

Added a section in the readme about it here: https://github.com/VictorBjelkholm/ipfsbin#raw-modeplain-text
